# Generated by Django 5.2.7 on 2025-11-18 00:24

from django.db import migrations, models
from django.db import connection


def add_name_field_if_missing(apps, schema_editor):
    """Add name field to DashboardTab if it doesn't exist."""
    db_alias = schema_editor.connection.alias
    DashboardTab = apps.get_model('buysellapi', 'DashboardTab')
    
    # Check if table exists and if name column exists
    with schema_editor.connection.cursor() as cursor:
        # Database-agnostic way to check if column exists
        vendor = connection.vendor
        
        if vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(buysellapi_dashboardtab)")
            columns = [row[1] for row in cursor.fetchall()]
            
            if 'name' not in columns:
                # Add the name column with a default value
                cursor.execute("""
                    ALTER TABLE buysellapi_dashboardtab 
                    ADD COLUMN name varchar(120) NOT NULL DEFAULT ''
                """)
                # Update existing rows to use slug as name if name is empty
                cursor.execute("""
                    UPDATE buysellapi_dashboardtab 
                    SET name = slug WHERE name = '' OR name IS NULL
                """)
        elif vendor == 'postgresql':
            # Check if column exists
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='buysellapi_dashboardtab' AND column_name='name'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE buysellapi_dashboardtab 
                    ADD COLUMN name varchar(120) NOT NULL DEFAULT ''
                """)
                cursor.execute("""
                    UPDATE buysellapi_dashboardtab 
                    SET name = slug WHERE name = '' OR name IS NULL
                """)
        elif vendor == 'mysql':
            cursor.execute("""
                SELECT COLUMN_NAME 
                FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'buysellapi_dashboardtab' 
                AND COLUMN_NAME = 'name'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE buysellapi_dashboardtab 
                    ADD COLUMN name varchar(120) NOT NULL DEFAULT ''
                """)
                cursor.execute("""
                    UPDATE buysellapi_dashboardtab 
                    SET name = slug WHERE name = '' OR name IS NULL
                """)


def reverse_add_name_field(apps, schema_editor):
    """Remove name field (reverse migration - not fully supported for SQLite)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0047_quickorderproduct'),
    ]

    operations = [
        migrations.RunPython(add_name_field_if_missing, reverse_add_name_field),
    ]
