# Generated by Django 5.2.7 on 2025-11-18 00:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('buysellapi', '0048_add_dashboardtab_name_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create the ManyToMany relationship tables if they don't exist
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS buysellapi_dashboardtab_groups (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                dashboardtab_id BIGINT NOT NULL REFERENCES buysellapi_dashboardtab(id) DEFERRABLE INITIALLY DEFERRED,
                group_id INTEGER NOT NULL REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED,
                UNIQUE(dashboardtab_id, group_id)
            );
            CREATE INDEX IF NOT EXISTS buysellapi_dashboardtab_groups_dashboardtab_id_03bbc691 
                ON buysellapi_dashboardtab_groups(dashboardtab_id);
            CREATE INDEX IF NOT EXISTS buysellapi_dashboardtab_groups_group_id_caf56fbe 
                ON buysellapi_dashboardtab_groups(group_id);
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS buysellapi_dashboardtab_groups;
            """
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS buysellapi_dashboardtab_users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                dashboardtab_id BIGINT NOT NULL REFERENCES buysellapi_dashboardtab(id) DEFERRABLE INITIALLY DEFERRED,
                user_id INTEGER NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
                UNIQUE(dashboardtab_id, user_id)
            );
            CREATE INDEX IF NOT EXISTS buysellapi_dashboardtab_users_dashboardtab_id_15949f62 
                ON buysellapi_dashboardtab_users(dashboardtab_id);
            CREATE INDEX IF NOT EXISTS buysellapi_dashboardtab_users_user_id_43313e98 
                ON buysellapi_dashboardtab_users(user_id);
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS buysellapi_dashboardtab_users;
            """
        ),
    ]
