# Generated by Django 5.2.7 on 2025-11-18 00:43

from django.db import migrations
from django.db import connection


def add_description_field_if_missing(apps, schema_editor):
    """Add description field to DashboardTab if it doesn't exist."""
    db_alias = schema_editor.connection.alias
    DashboardTab = apps.get_model('buysellapi', 'DashboardTab')
    
    # Check if table exists and if description column exists
    with schema_editor.connection.cursor() as cursor:
        # Database-agnostic way to check if column exists
        vendor = connection.vendor
        
        if vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(buysellapi_dashboardtab)")
            columns = [row[1] for row in cursor.fetchall()]
            
            if 'description' not in columns:
                # Add the description column with a default value
                cursor.execute("""
                    ALTER TABLE buysellapi_dashboardtab 
                    ADD COLUMN description text NOT NULL DEFAULT ''
                """)
        elif vendor == 'postgresql':
            # Check if column exists
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='buysellapi_dashboardtab' AND column_name='description'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE buysellapi_dashboardtab 
                    ADD COLUMN description text NOT NULL DEFAULT ''
                """)
        elif vendor == 'mysql':
            cursor.execute("""
                SELECT COLUMN_NAME 
                FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'buysellapi_dashboardtab' 
                AND COLUMN_NAME = 'description'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE buysellapi_dashboardtab 
                    ADD COLUMN description text NOT NULL DEFAULT ''
                """)


def reverse_add_description_field(apps, schema_editor):
    """Remove description field (reverse migration - not fully supported for SQLite)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0049_create_dashboardtab_m2m_tables'),
    ]

    operations = [
        migrations.RunPython(add_description_field_if_missing, reverse_add_description_field),
    ]
